Update README.md
seriouslysean/monster-hunter-now-events pull request #40
Opened 2023-10-15 08:04 UTC by ISaumya1011

Please check the changes I've made according to your requirements  now. If any further changes need to be done, please let me know. N also, If you merge these changes, kindly accept my commits under hacktoberfest2023. Also, if possible please see if you can accept these changes against #28 and #30 both as it is necessary for my task completion under hacktoberfest2023. Thank you!

## Issue

Relevant [issue number](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)
- Resolves #

## Testing Steps

1.

## Additional Information

1.

2023-10-15 10:02 UTC, seriouslysean requested changes
The tone of the message is still being changed in a way I don't really like, and the overall organization doesn't match expectations.

I've left some more feedback if you're interested in continuing to refine it, though. I think a better understanding of what the project does might help, so it's a bit more clear where the elements belong.

If you're mostly interested in having this merged for hacktoberfest, it might be easier to start with just the spelling mistakes to resolve #28.

Thanks again for the time you've spent on this!

2023-10-15 10:02 UTC, seriouslysean commented on docs/README.md
> +## Table Of Contents &#128203;
Remove this title entirely, it duplicates the goal of the main heading.

```suggestion
```

2023-10-15 10:02 UTC, seriouslysean commented on docs/README.md
> +## Calendar Subscription &#128198;
```suggestion
## Calendar Subscription
```

Remove the encoded entity.

2023-10-15 10:02 UTC, seriouslysean commented on docs/README.md
> +In case you are not playing yet, you can join and play the game with me and my friends. [Feel free to join ](https://apps.apple.com/us/app/monster-hunter-now/id6445906110) and use my **referral code*
This changes the tone be much more formal, leave it informal and just fix any spelling mistakes. You added bold tags around a code block, remove those.

2023-10-15 10:02 UTC, seriouslysean commented on docs/README.md
> +'''
You changed the three backticks denoting a code block to 3 single quotes which do not serve the same purpose, switch those back, please.

2023-10-15 10:02 UTC, seriouslysean commented on docs/README.md
> +## Local Implementation of Calendar Subscription
Leave this as "Run Locally". This change is too verbose.

2023-10-15 10:02 UTC, seriouslysean commented on docs/README.md
> +### * Open AI Key
These titles now start with an asterisk but shouldn't, remove those please.

2023-10-15 10:02 UTC, seriouslysean commented on docs/README.md
> -### Tools
This should still be an h3 as they're developer centric tools which fall under run locally.

2023-10-15 10:02 UTC, seriouslysean commented on docs/README.md
> +* Download, Parse and Save One Article
This is strictly a formatting change and doesn't change anything about the visual display.

2023-10-15 10:02 UTC, seriouslysean commented on docs/README.md
> +## References &#128187;
Remove the entity.

2023-10-15 10:18 UTC, seriouslysean commented
Copying this here from #39 as it’s a helpful bit of context.

> Based on the naming of the branches, you’re making changes directly via GitHub. It might be worth learning to pull the changes down locally and using an editor instead.
> 
> https://code.visualstudio.com/docs/sourcecontrol/intro-to-git
> 
> Hope this helps!

2023-10-15 11:00 UTC, ISaumya1011 commented
Okay, thank you for the feedback! Actually my exams are approaching and I
will not be able to devote too much time on the project. Please allocate me
#28 . I'll complete it by EOD and provide the changes for the same. Will
look forward to work with you in the future!

On Sun, 15 Oct, 2023, 3:48 pm Sean Kennedy, ***@***.***>
wrote:

> Copying this here from #39
> <https://github.com/seriouslysean/monster-hunter-now-events/pull/39> as
> it’s a helpful bit of context.
>
> Based on the naming of the branches, you’re making changes directly via
> GitHub. It might be worth learning to pull the changes down locally and
> using an editor instead.
>
> https://code.visualstudio.com/docs/sourcecontrol/intro-to-git
>
> Hope this helps!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/seriouslysean/monster-hunter-now-events/pull/40#issuecomment-1763344796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BCCV6BTJHMQQAHZVPWPI5ILX7O2ABANCNFSM6AAAAAA6A2TL4U>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-10-24 00:07 UTC, seriouslysean commented
Closed in favor of https://github.com/seriouslysean/monster-hunter-now-events/pull/50.

2023-10-24 00:07 UTC, closed without merging